{
 "title": "Sensors",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temp / Humidity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Humidity",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dhtmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temphumid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humid\")\n  |> group(columns: [\"sensor\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"sensor\"])"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"dhtmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temphumid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> group(columns: [\"sensor\"])\n  |> last()\n  |> keep(columns: [\"_time\", \"_value\", \"sensor\"])"
      }
     ]
    },
    {
     "title": "Last seen",
     "type": "stat",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket:\"dhtmon\") \n|> range(start:-2d) \n|> filter(fn: (r) => r._field == \"temp\") \n|> group(columns: [\"sensor\"]) \n|> last() \n|> keep(columns: [\"_time\", \"sensor\"]) \n|> map(fn: (r) => ({r with ds: (int(v: now()) - int(v: r._time)) / 1000000000 }))"
      }
     ]
    }
   ]
  },
  {
   "title": "Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "query": "from(bucket: \"dhtmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temphumid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humid\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"dhtmon\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temphumid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  }
 ]
}